# use ubuntu trusty for newer version of nodejs, used for JS testing
dist: trusty

# faster builds on new travis setup not using sudo
# temporary disable, see https://github.com/travis-ci/travis-ci/issues/6842
#sudo: false
sudo: required

group: edge

language: php

env:
  global:
    - DEFAULT_COMPOSER_FLAGS="--prefer-dist --no-interaction --no-progress --optimize-autoloader"
    - TASK_TESTS_PHP=1
    - TASK_TESTS_JS=0
    - TASK_TESTS_COVERAGE=0

matrix:
  fast_finish: true
  include:
    - php: 7.2
    - php: 7.3
      env: TASK_TESTS_COVERAGE=1
    - php: nightly

    # have a separate branch for javascript tests
    - language: node_js
      node_js: 6
      php: 7.3
      env: TASK_TESTS_PHP=0 TASK_TESTS_JS=1
      # overwrite services used for PHP tests
      services:

# cache vendor dirs
cache:
  directories:
    - vendor
    - $HOME/.composer/cache
    - $HOME/.npm

install:
  # setup PHP tests
  - |
    if [ $TASK_TESTS_PHP == 1 ]; then
      travis_retry composer self-update && composer --version
      export PATH="$HOME/.composer/vendor/bin:$PATH"
      travis_retry composer install --prefer-dist --no-interaction
    fi

  # setup JS tests
  - |
    if [ $TASK_TESTS_JS == 1 ]; then
      travis_retry npm install
    fi

before_script:
  - |
    if [ $TRAVIS_PHP_VERSION = '7.3' ]; then
      PHPUNIT_FLAGS="--coverage-clover=coverage.clover"
    fi
  - |
    if [ $TASK_TESTS_JS == 1 ]; then
      node --version
      npm --version
    fi

script:
  # PHP tests
  - |
    if [ $TASK_TESTS_PHP == 1 ]; then
      ./vendor/bin/phpunit $PHPUNIT_FLAGS
    fi

  # JS tests
  - |
    if [ $TASK_TESTS_JS == 1 ]; then
      npm test
    fi

notifications:
  slack:
    -
      rooms:
        -
          secure: d2VSpvSpJ5GmfQOOs7Kc0erqG+uNgHcjbdQ1wG9/rYMwlpO1AWDT8NTOJrZuEgKVMrdhf3lm5E+Of/oPWTcVoCCLFfDByAh5g9r1/nmYILSsI8DjDs9xx412nce31iMt6a/BBPCtaY26TiBCR7f+baL6FxFOTgEp0dPRPV+SIkpT1+IGV7WnGAr0qPdWOYL+3TWrWnqa4q0o7pFeULzNev+fK2bDp7umfA3BqWwfXMCKrWTY4Sjx8VAjLDtz+Y7SrEX6CZdMydS1x97Qygd9CAAebWgLB2lc5OYSlUMbz71sOO3OyHV57ruktCDF3O3Cah/P/DoBKziemifsPiqePWRlXOWbqQMlniyXjOf6JjZamWDxYMG3qKOZyPaWiAQ6Ko92bPqs/9p9dppWg5IR+M7JiPkpDXiSsAv6K2yJBK0YzijhMOSgaTRznUOJmRBKAlWpD7d2KQ+wBDQs2rjphNhMXvoE7zmbljW4cnBK7l8HCqHc6Ws61ca/DdA++6jG4sCSBSqWqNJEnfF4eChf3C6z5z/46u82WlXwmWClWcya2WcN+5aw0bTUOjm6YI1T3jddmBXgNkG20bDZSNZwVOjmLBiDh9hcFTNgAwu7S6AmzuaeD0QH5NddrwvF99y6+ZjIMi4z5Hr3vM6IJl32iBbWTTaKCjBfgmWOzARSYOA=
      on_success: always
      on_failure: never
      on_pull_requests: false
    -
      rooms:
        -
          secure: PY7XNEe168kPgHWm/bg01IrxOwzidwIepJsLPfZAM8i+XsvlmyNroFAUW32U1vJZpMiitMYpeYO9KbCyrjT2bdEItwD7deKOzid6QCTjvFnyQkqSYZzzusvCUvP5uAyVPBnIQMR/7VqBwrNC71CgEcBUJXVdaM7VDWD1oiyD6o3ntTDe8yztPguzzXGb6dGhpTTAHhjn45/9S3w8I2KCmlQgwwxbI/YZv9LPzDG/7Vje8akWroBSG+N2y2NomLnvS9e5n6FHvTprb4GT9p8PINOKD9bgvP3w/zqoLSkiJjmg2vKhzBKwsQRVvYrXzHe+tKlxVvJEnh2qvjV7DMKBa/LdwDe3thhWAiZDYUMrW2D6EiqfCWIfnvbgB1PyIGCjOjTSDAVnc70SAKUUsqzJxCxmrw6A4z+BDmOjkK589eEmWkAKHmhgRBHfv0aodryEj3J+2lTCvcZC8bEJyirvxPYVkl+ZQtdqMpAiolzZLKGQIbNIJQvCKwihXLAHb7kOVjojqpNtsLLQ9pzrMeAGuDhaw87ZB6uO3zANEzFhCb5C/IPOFbgYKBn7Z8c9pFWgzr4uzPNabqb6Lk1G0jSnlpHbIcwRZLb6xSlto6NpTFvehkoIdxeaXt+TxS3eiNabX+lN1ekB6pO4uzm3fcIAjB+51Pp+lkWyRQi9Mo/b+O0=
      on_success: never
      on_failure: always
      on_pull_requests: false
